---

- name: Provision macOS
  hosts: localhost
  connection: local
  vars:
    gecko_version: "0.19.1"
    chromedriver_version: "2.35"
    bitbar_version: "1.9.2"
    homebrew_api_token: "{{ lookup('file', 'homebrew_token')}}"
  tasks:
    - set_fact: user="{{ lookup('env', 'USER')}}"
      tags: always
    - debug: var=user
      tags: always

    - name: ~/bin
      file: path="/Users/{{ user }}/bin" state=directory mode=0755
      tags: bin

    - name: ~/Applications
      file: path="/Users/{{ user }}/Applications" state=directory mode=0755

    - import_tasks: tasks/pip.yml
    - import_tasks: tasks/oh-my-zsh.yml
    - import_tasks: tasks/homebrew.yml
    - import_tasks: tasks/nvm.yml
      tags: nvm
    - import_tasks: tasks/fonts.yml
    - import_tasks: tasks/bitbar.yml
    - import_tasks: tasks/scripts.yml
    - import_tasks: tasks/geckodriver.yml
      tags: geckodriver
    - import_tasks: tasks/chromedriver.yml
      tags: chromedriver
    - import_tasks: tasks/hosts.yml
