---

- name: Provision macOS
  hosts: localhost
  connection: local
  vars:
    gecko_version: "0.18.0"
    chromedriver_version: "2.30"
    bitbar_version: "1.9.2"
  tasks:
    - set_fact: user="{{ lookup('env', 'USER')}}"
      tags: always
    - debug: var=user
      tags: always

    - name: ~/bin
      file: path="/Users/{{ user }}/bin" state=directory mode=0755
      tags: bin

    - include: tasks/pip.yml
    - include: tasks/oh-my-zsh.yml
    - include: tasks/homebrew.yml
    - include: tasks/nvm.yml
      tags: nvm
    - include: tasks/fonts.yml
    - include: tasks/bitbar.yml
    - include: tasks/geckodriver.yml
      tags: geckodriver
    - include: tasks/chromedriver.yml
      tags: chromedriver
