---

- name: Provision macOS
  hosts: localhost
  connection: local
  vars:
    gecko_version: "0.24.0"
    chromedriver_version: "91.0.4472.101"
    bitbar_version: "1.9.2"
    docker_cred_helper_version: "0.6.4"
    graalvm:
      enabled: True
      version: "21.0.0"
    user: "{{ lookup('env', 'USER')}}"
  vars_files:
    - vars/secrets
  tasks:
    - debug: var=user
      tags: always

    - name: ~/bin
      file: path="/Users/{{ user }}/bin" state=directory mode=0755
      register: user_bin
      tags: bin

    - name: ~/Applications
      file: path="/Users/{{ user }}/Applications" state=directory mode=0755

    - import_tasks: tasks/python.yml
    - import_tasks: tasks/pip.yml
    - import_tasks: tasks/oh-my-zsh.yml
    - import_tasks: tasks/homebrew.yml
    - import_tasks: tasks/nvm.yml
      tags: nvm
    - import_tasks: tasks/fonts.yml
    - import_tasks: tasks/bitbar.yml
    - import_tasks: tasks/scripts.yml
    - import_tasks: tasks/fzf.yml
      tags: fzf
    - import_tasks: tasks/lein.yml
      tags: lein
    - import_tasks: tasks/geckodriver.yml
      tags: geckodriver
    - import_tasks: tasks/chromedriver.yml
      tags: chromedriver
    - import_tasks: tasks/hosts.yml
    - import_tasks: tasks/graalvm.yml
      when: graalvm.enabled
      tags: graalvm
    - import_tasks: tasks/docker.yml
      tags: docker
  roles:
    - role: aws-profile
      tags: aws
