---

- name: brew install --cask alacritty
  community.general.homebrew_cask:
    name: alacritty 
    state: present

- name: alacritty config file
  copy: src=files/alacritty.yml dest="{{ xdg_config_home }}/alacritty.yml"
