---

- name: bat | brew install
  homebrew:
    name: bat
    state: latest
  tags:
    - brew-latest

- name: bat | get config file path
  command: bat --config-file
  register: bat_config_file

- name: bat | config dir
  file:
    state: directory
    path:  "{{ bat_config_file.stdout | dirname }}"

- name: bat | config
  copy:
    src: files/bat.config
    dest: "{{ bat_config_file.stdout }}"
