---

- name: Docker Desktop
  community.general.homebrew_cask:
    name: docker
    state: present
  tags:
    - sudo

- name: Docker credentials helper
  block:
    - name: ~/bin/docker-herlper
      ansible.builtin.file:
        path: "~/bin/docker-helper"
        state: directory
    - name: Download helper
      ansible.builtin.get_url:
        url: "https://github.com/docker/docker-credential-helpers/releases/download/v{{ docker_cred_helper.version }}/docker-credential-osxkeychain-v{{ docker_cred_helper.version }}.darwin-{{ ansible_architecture }}"
        dest: "~/bin/docker-helper"
        checksum: "{{ docker_cred_helper.checksum[ansible_architecture] }}"

- name: Docker config
  block:
    - name: ~/.docker
      ansible.builtin.file:
        path: "~/.docker"
        state: directory
    - name: Docker config.json
      ansible.builtin.template:
        src: docker-config.json.j2
        dest: "~/.docker/config.json"
