---

- name: Powerline fonts from Github
  git:
    repo: https://github.com/powerline/fonts.git
    dest: "/Users/{{ user }}/fonts"
  tags: fonts

- name: Install fonts
  command: "/Users/{{ user }}/fonts/install.sh"
  args:
    chdir: "/Users/{{ user }}/fonts"
  tags: fonts


- name: ~/Solarized
  file: path="/Users/{{ user }}/Solarized" state=directory mode=0755
  tags:
    - fonts
    - solarized

- name: Solarized theme
  git:
    repo: https://github.com/altercation/solarized.git
    dest: "/Users/{{ user }}/Solarized"
  tags:
    - fonts
    - solarized
