---

- name: Install Homebrew packages
  homebrew: name={{ brew_packages }} state=present
  tags:
    - brew
    - brew-packages

- name: Install Homebrew state=latest packages
  homebrew: name={{ brew_latest_packages }} state=latest
  tags:
   - brew
   - brew-latest

- name: Install caskroom/versions
  command: brew tap homebrew/cask-versions
  tags:
    - brew
    - brew-versions

- name: Install homebrew-cask packages
  community.general.homebrew_cask: 
    name: "{{ brew_casks }}"
  tags:
    - brew
    - brew-cask

- name: Ping certain brew forumales
  command: brew pin {{ item }}
  loop:
    - gcc
  register: brew_pin
  changed_when: '"already pinned" not in brew_pin.msg'
  tags:
    - brew
    - brew-pin
