---

- name: Install Homebrew packages
  community.general.homebrew: name={{ brew_packages }} state=present install_options=quiet
  register: brew_packages
  tags:
    - brew
    - brew-packages

- name: "Changed packages" 
  debug: var=brew_packages.changed_pkgs
  check_mode: no
  tags:
    - brew
    - brew-packages

- name: Install Homebrew state=latest packages
  community.general.homebrew: name={{ brew_latest_packages }} state=latest install_options=quiet
  register: brew_latest_packages
  tags:
   - brew
   - brew-latest

- name: "Changed latest packages" 
  debug: var=brew_latest_packages.changed_pkgs
  check_mode: no
  when: brew_latest_packages.changed_pkgs
  tags:
    - brew
    - brew-packages

- name: Install homebrew-cask packages
  community.general.homebrew_cask:
    name: "{{ brew_casks }}"
    install_options: quiet
  tags:
    - brew
    - brew-cask

- name: Pin certain brew forumales
  command: brew pin {{ item }}
  loop:
    - gcc
  register: brew_pin
  changed_when: '"already pinned" not in brew_pin.msg'
  tags:
    - brew
    - brew-pin

- name: Homebrew shellenv to .zprofile
  lineinfile:
    create: yes
    path: "/Users/{{ user }}/.zprofile"
    regexp: 'brew shellenv'
    line: 'eval "$(brew shellenv)"'
  tags:
    - brew
    - zprofile
