---

- name: Install homebrew packages
  homebrew: name={{ brew_packages }} state=present
  tags: brew

- name: Install coreutils via brew
  homebrew: name={{ brew_coreutils }} state=latest
  tags:
   - brew
   - coreutils

- name: Install caskroom/versions
  command: brew tap homebrew/cask-versions
  register: versions_tap
  changed_when: versions_tap.stdout != ""
  tags:
    - brew
    - brew-versions

- name: Install homebrew-cask packages
  command: brew cask install {{ brew_casks | join(' ') }}
  register: cask_install
  changed_when: '"already installed" not in cask_install.stderr'
  tags:
    - brew
    - brew-cask

- name: Install hombrew-services
  command: brew tap homebrew/services
  register: services_tap
  changed_when: services_tap.stdout != ""
  tags:
    - brew
    - brew-services

- name: Start services via homebrew-services
  command: brew services start {{item}}
  with_items: "{{ brew_services }}"
  register: services_start
  changed_when: '"already started" not in services_start.stdout'
  tags:
    - brew
    - brew-services
