---

- name: Install homebrew packages
  homebrew: name={{ brew_packages }} state=present
  tags: brew

- name: Install homebrew with latest versions
  homebrew: name={{ brew_latest_packages }} state=latest
  tags:
   - brew
   - brew-latest

- name: Install caskroom/versions
  command: brew tap homebrew/cask-versions
  tags:
    - brew
    - brew-versions

- name: Install homebrew-cask packages
  homebrew: name={{ brew_casks }} install_options=quiet,cask
  tags:
    - brew
    - brew-cask

- name: Install hombrew-services
  command: brew tap homebrew/services
  tags:
    - brew
    - brew-services

#- name: Start services via homebrew-services
#  command: brew services start {{item}}
#  with_items: "{{ brew_services }}"
#  register: services_start
#  changed_when: '"already started" not in services_start.stdout'
#  when: brew_services is defined and brew_services
#  tags:
#    - brew
#    - brew-services

- name: Ping certain brew forumales
  command: brew pin {{ item }}
  loop:
    - gcc
  register: brew_pin
  changed_when: '"already pinned" not in brew_pin.msg'
  tags:
    - brew
    - brew-ping
