---

- name: Install Homebrew packages
  homebrew: name={{ brew_packages }} state=present
  tags:
    - brew
    - brew-packages

- name: Install Homebrew state=latest packages
  homebrew: name={{ brew_latest_packages }} state=latest
  tags:
   - brew
   - brew-latest

- name: Install caskroom/versions
  command: brew tap homebrew/cask-versions
  tags:
    - brew
    - brew-versions

- name: Install homebrew-cask packages
  community.general.homebrew_cask:
    name: "{{ brew_casks }}"
  tags:
    - brew
    - brew-cask

- name: Pin certain brew forumales
  command: brew pin {{ item }}
  loop:
    - gcc
  register: brew_pin
  changed_when: '"already pinned" not in brew_pin.msg'
  tags:
    - brew
    - brew-pin

- name: Homebrew shellenv to .zprofile
  lineinfile:
    create: yes
    path: "/Users/{{ user }}/.zprofile"
    regexp: 'brew shellenv'
    line: 'eval "$(brew shellenv)"'
  tags:
    - brew
    - zprofile
