---

- shell: /usr/libexec/java_home -v$(/usr/libexec/java_home -V  2>&1 | head -n2 | tail -n1 | cut -d' ' -f5)
  register: java_path

- name: JAVA_HOME for launchctl setenv
  command: launchctl setenv JAVA_HOME "{{ java_path.stdout }}"
