---

- name: Install NVM via homebrew
  homebrew: name=nvm state=present

- name: ~/.nvm
  file: path="/Users/{{ user }}/.nvm" state=directory owner={{ user }}

# NVM to .zshenv for compability https://github.com/SublimeLinter/SublimeLinter3/issues/128
- name: Ensure NVM_DIR to .zshenv
  lineinfile: path="/Users/{{ user }}/.zshenv" regexp='^export NVM_DIR=' line='export NVM_DIR="/Users/{{ user }}/.nvm"'
  tags:
    - zshrc

- name: Source nvm from ~/.zshenv
  lineinfile:
    path: "/Users/{{ user }}/.zshenv"
    regexp: '^\. "\/usr\/local\/opt\/nvm\/nvm.\sh"'
    insertafter: '^export NVM_DIR='
    line: '. "/usr/local/opt/nvm/nvm.sh"'
  tags:
    - zshrc

