---

- file: path="/Users/{{ user }}/.oh-my-zsh" state=directory mode=0755 owner="{{ user }}"
  tags: zsh

- name: Clone oh-my-zsh repo
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: "/Users/{{ user }}/.oh-my-zsh"
  tags: zsh

- name: .zsh* files
  template: src=templates/{{ item }}.j2 dest="/Users/{{ user }}/.{{ item }}" owner={{ user }}
  loop:
    - zshrc
    - zshenv
  tags:
    - zsh
    - zshrc

- name: Clone powerline10k zsh theme
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: /Users/{{ user }}/.oh-my-zsh/custom/themes/powerlevel10k
  tags: zsh

- name: Set Homebrew zsh as default shell
  become: yes
  user: name={{ user }} shell=/usr/local/bin/zsh
  tags:
    - zsh
    - sudo
