---

#- name: Install pip global packages
#  become: no
#  pip: name="{{ item.name }}" version="{{ item.version | default(omit) }}" use_mirrors=no
#  loop:
#  tags: pip

- name: Install pip user packages
  become: no
  pip: name="{{ item.name }}" version="{{ item.version | default(omit) }}" extra_args="--user"
  loop:
    - { name: powerline-status }
    - { name: thefuck }
    - { name: awscli }
    - { name: cryptography }
    - { name: netaddr }
    - { name: apache-libcloud }
    - { name: pycrypto }
    - { name: requests }
    - { name: google-auth }
    - { name: openshift }
    - { name: docker }
    - { name: git-of-theseus }
  tags: pip
