---

- name: Check Python3 version
  command: python3 --version
  register: python_version_string
  tags: always

- name: Python3 user site location
  command: python3 -m site --user-site
  register: python_user_site
  tags: always

- set_fact:
    python_version_full: "{{ python_version_string.stdout | regex_replace('^Python (\\d\\.\\d\\.\\d)', '\\1') }}"
    python_version: "{{ python_version_string.stdout | regex_replace('^Python (\\d\\.\\d)\\.\\d', '\\1') }}"
  tags: always

- name: Symlink Python 3 to /Library/Frameworks
  become: true
  file:
    src: "/usr/local/Cellar/python/{{ python_version_full }}/Frameworks/Python.framework"
    dest: /Library/Frameworks/Python.framework
    mode: 0775
    state: link
  tags:
    - python
    - sudo
