---

- name: .aws folder
  file:
    dest: "/Users/{{ user }}/.aws"
    state: directory


- name: Install latest of aws-vault
  homebrew: name=aws-vault state=present
  tags:
    - brew
    - aws-vault

- name: .aws/config
  template:
    src: "templates/config.j2"
    dest: "/Users/{{ user }}/.aws/config"
    owner: "{{ user }}"
  when: "'aws-config' in ansible_run_tags"
  tags:
    - aws-config
