---

- name: .aws folder
  file:
    dest: "/Users/{{ user }}/.aws"
    state: directory


- name: Install latest of aws-vault
  homebrew: name=aws-vault state=latest
  tags:
    - brew
    - aws-vault

- name: Templates to .aws
  template:
    src: "templates/{{ item }}.j2"
    dest: "/Users/{{ user }}/.aws/{{ item }}"
    owner: "{{ user }}"
  loop:
    - config

## Use aws-vault to store access tokens
