---

# https://podman.io/getting-started/installation#macos
# Next, create and start your first Podman machine:
#
# podman machine init
# podman machine start
#
# You can then verify the installation information using:
#
# podman info

- name: Podman from Homebrew
  homebrew:
    name:
      - podman
#      - podman-compose
    state: latest
  tags:
   - brew
   - brew-latest


- name: Podman Desktop
  homebrew: name=podman-desktop state=latest install_options=cask
  register: cask_install
  changed_when: '"already installed" not in cask_install.msg'
  failed_when: '"installed" not in cask_install.msg'
  tags:
   - brew
   - brew-latest

