---

- name: Install zsh from brew
  homebrew: name=zsh state=present
  tags:
    - brew

- name: Set Homebrew zsh as default shell
  become: yes
  user: name={{ user }} shell="{{ brew_prefix }}/bin/zsh"
  tags:
    - sudo

# https://gist.github.com/SheldonWangRJT/8d3f44a35c8d1386a396b9b49b43c385
- name: ~/zsh-functions
  copy:
    src: functions/
    dest: "/Users/{{ user }}/zsh-functions"
    mode: u+rwx,g-wx,o-rwx
  tags:
    - zfuncs
    - zshfunctions

- file: path="/Users/{{ user }}/.oh-my-zsh" state=directory mode=0755 owner="{{ user }}"

- name: Clone oh-my-zsh repo
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: "/Users/{{ user }}/.oh-my-zsh"

- name: .zshrc from template
  template: src=templates/zshrc.j2 dest="/Users/{{ user }}/.zshrc" owner={{ user }} backup=yes
  tags:
    - zshrc
    - zfuncs
    - zshfunctions

- name: Clone powerline10k zsh theme
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: /Users/{{ user }}/.oh-my-zsh/custom/themes/powerlevel10k
    depth: 1
  tags:
    - p10k

- name: zsh-syntax-highlight
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest:  /Users/{{ user }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

