---

- name: brew install neovim
  homebrew: name=neovim state=latest

- name: nvim dirs
  file: state=directory path="{{ item }}"
  loop:
    - "{{ nvim_config_dir }}"
    - "{{ nvim_data_dir }}"
    - "{{ nvim_lua_dir }}"

- name: paq from GitHub
  ansible.builtin.git:
    repo: git@github.com:savq/paq-nvim.git
    dest: "{{ nvim_data_dir }}/site/pack/paqs/start/paq-nvim"
    depth: 1

- name: vimrc
  template: src=init.vim.j2 dest="{{ nvim_config_dir }}/init.vim"
  tags:
    - vimrc

- name: plugins.lua
  template: src=plugins.lua.j2 dest="{{ nvim_config_dir }}/lua/plugins.lua"
  tags: vimrc


- name: Install plugins
  command: nvim --headless -u NONE -c 'lua require("plugins")'
  register: install
  changed_when: "install.stderr != ' Paq: Nothing to install'"
  tags: vimrc

- debug: var=install


  #     global
  # List of directories to be searched for these runtime files:
  #   filetype.vim  filetypes by file name |new-filetype|
  #   scripts.vim filetypes by file contents |new-filetype-scripts|
  #   autoload/ automatically loaded scripts |autoload-functions|
  #   colors/ color scheme files |:colorscheme|
  #   compiler/ compiler files |:compiler|
  #   doc/    documentation |write-local-help|
  #   ftplugin/ filetype plugins |write-filetype-plugin|
  #   indent/ indent scripts |indent-expression|
  #   keymap/ key mapping files |mbyte-keymap|
  #   lang/   menu translations |:menutrans|
  #   menu.vim  GUI menus |menu.vim|
  #   pack/   packages |:packadd|
  #   plugin/ plugin scripts |write-plugin|
  #   print/  files for printing |postscript-print-encoding|
  #   rplugin/  |remote-plugin| scripts
  #   spell/  spell checking files |spell|
  #   syntax/ syntax files |mysyntaxfile|
  #   tutor/  tutorial files |:Tutor|
